package com.cuipengyu.solitarysoulbook.entity.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.cuipengyu.solitarysoulbook.entity.bean.UserBean;
import com.cuipengyu.solitarysoulbook.entity.bean.UserHisitoryBean;
import com.cuipengyu.solitarysoulbook.entity.bean.UserInforMation;
import com.cuipengyu.solitarysoulbook.entity.bean.UserShelfBean;

import com.cuipengyu.solitarysoulbook.entity.db.UserBeanDao;
import com.cuipengyu.solitarysoulbook.entity.db.UserHisitoryBeanDao;
import com.cuipengyu.solitarysoulbook.entity.db.UserInforMationDao;
import com.cuipengyu.solitarysoulbook.entity.db.UserShelfBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig userBeanDaoConfig;
    private final DaoConfig userHisitoryBeanDaoConfig;
    private final DaoConfig userInforMationDaoConfig;
    private final DaoConfig userShelfBeanDaoConfig;

    private final UserBeanDao userBeanDao;
    private final UserHisitoryBeanDao userHisitoryBeanDao;
    private final UserInforMationDao userInforMationDao;
    private final UserShelfBeanDao userShelfBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        userBeanDaoConfig = daoConfigMap.get(UserBeanDao.class).clone();
        userBeanDaoConfig.initIdentityScope(type);

        userHisitoryBeanDaoConfig = daoConfigMap.get(UserHisitoryBeanDao.class).clone();
        userHisitoryBeanDaoConfig.initIdentityScope(type);

        userInforMationDaoConfig = daoConfigMap.get(UserInforMationDao.class).clone();
        userInforMationDaoConfig.initIdentityScope(type);

        userShelfBeanDaoConfig = daoConfigMap.get(UserShelfBeanDao.class).clone();
        userShelfBeanDaoConfig.initIdentityScope(type);

        userBeanDao = new UserBeanDao(userBeanDaoConfig, this);
        userHisitoryBeanDao = new UserHisitoryBeanDao(userHisitoryBeanDaoConfig, this);
        userInforMationDao = new UserInforMationDao(userInforMationDaoConfig, this);
        userShelfBeanDao = new UserShelfBeanDao(userShelfBeanDaoConfig, this);

        registerDao(UserBean.class, userBeanDao);
        registerDao(UserHisitoryBean.class, userHisitoryBeanDao);
        registerDao(UserInforMation.class, userInforMationDao);
        registerDao(UserShelfBean.class, userShelfBeanDao);
    }
    
    public void clear() {
        userBeanDaoConfig.clearIdentityScope();
        userHisitoryBeanDaoConfig.clearIdentityScope();
        userInforMationDaoConfig.clearIdentityScope();
        userShelfBeanDaoConfig.clearIdentityScope();
    }

    public UserBeanDao getUserBeanDao() {
        return userBeanDao;
    }

    public UserHisitoryBeanDao getUserHisitoryBeanDao() {
        return userHisitoryBeanDao;
    }

    public UserInforMationDao getUserInforMationDao() {
        return userInforMationDao;
    }

    public UserShelfBeanDao getUserShelfBeanDao() {
        return userShelfBeanDao;
    }

}
