package com.cuipengyu.solitarysoulbook.entity.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.cuipengyu.solitarysoulbook.entity.bean.UserInforMation;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "USER_INFOR_MATION".
*/
public class UserInforMationDao extends AbstractDao<UserInforMation, Long> {

    public static final String TABLENAME = "USER_INFOR_MATION";

    /**
     * Properties of entity UserInforMation.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserName = new Property(1, String.class, "userName", false, "USER_NAME");
        public final static Property UserImage = new Property(2, String.class, "userImage", false, "USER_IMAGE");
        public final static Property SignaTrue = new Property(3, String.class, "signaTrue", false, "SIGNA_TRUE");
    }


    public UserInforMationDao(DaoConfig config) {
        super(config);
    }
    
    public UserInforMationDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"USER_INFOR_MATION\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"USER_NAME\" TEXT," + // 1: userName
                "\"USER_IMAGE\" TEXT," + // 2: userImage
                "\"SIGNA_TRUE\" TEXT);"); // 3: signaTrue
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"USER_INFOR_MATION\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, UserInforMation entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(2, userName);
        }
 
        String userImage = entity.getUserImage();
        if (userImage != null) {
            stmt.bindString(3, userImage);
        }
 
        String signaTrue = entity.getSignaTrue();
        if (signaTrue != null) {
            stmt.bindString(4, signaTrue);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, UserInforMation entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userName = entity.getUserName();
        if (userName != null) {
            stmt.bindString(2, userName);
        }
 
        String userImage = entity.getUserImage();
        if (userImage != null) {
            stmt.bindString(3, userImage);
        }
 
        String signaTrue = entity.getSignaTrue();
        if (signaTrue != null) {
            stmt.bindString(4, signaTrue);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public UserInforMation readEntity(Cursor cursor, int offset) {
        UserInforMation entity = new UserInforMation( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // userImage
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3) // signaTrue
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, UserInforMation entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUserImage(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setSignaTrue(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(UserInforMation entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(UserInforMation entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(UserInforMation entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
